/*
 *    CimBios.TypeLib.Gost58651 - GOST 58651 CIM canonical model C# classes impementation
 *    Copyright (C) 2025 Yuri A. Kovalenko a.k.a belizahrt <belizahrt@gmail.com>
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 *	CimBios Toolkit autogenerated CIM type library code.
 */

using CimBios.Core.CimModel.DatatypeLib;
using CimBios.Core.CimModel.DatatypeLib.OID;
using CimBios.Core.CimModel.DatatypeLib.TypeLib;
using CimBios.Core.CimModel.Schema;

namespace CimBios.Gost58651.TypeLib;

/// <summary>
/// Дробь, указанная явно с числителем и знаменателем, которые можно использовать для вычисления частного.
/// </summary>
[CimClass(ClassUri)]
public partial class Ratio(IOIDDescriptor oid, ICimMetaClass metaClass)
    : Resource(oid, metaClass)
{
    public new const string ClassUri = "http://iec.ch/TC57/CIM100#Ratio";

    /// <summary>
    /// Знаменатель.
    /// </summary>
    public float? denominator
    {
        get => GetAttribute<float?>(nameof(denominator));
        set => SetAttribute(nameof(denominator), value);
    }

    /// <summary>
    /// Числитель.
    /// </summary>
    public float? numerator
    {
        get => GetAttribute<float?>(nameof(numerator));
        set => SetAttribute(nameof(numerator), value);
    }
}